# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@gar/promisify-1.1.3" = {
      name = "_at_gar_slash_promisify";
      packageName = "@gar/promisify";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@gar/promisify/-/promisify-1.1.3.tgz";
        sha512 = "k2Ty1JcVojjJFwrg/ThKi2ujJ7XNLYaFGNB/bWT9wGR+oSMJHMa5w+CUq6p/pVrKeNNgA7pCqEcjSnHVoqJQFw==";
      };
    };
    "@npmcli/fs-2.1.0" = {
      name = "_at_npmcli_slash_fs";
      packageName = "@npmcli/fs";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@npmcli/fs/-/fs-2.1.0.tgz";
        sha512 = "DmfBvNXGaetMxj9LTp8NAN9vEidXURrf5ZTslQzEAi/6GbW+4yjaLFQc6Tue5cpZ9Frlk4OBo/Snf1Bh/S7qTQ==";
      };
    };
    "@npmcli/move-file-2.0.0" = {
      name = "_at_npmcli_slash_move-file";
      packageName = "@npmcli/move-file";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@npmcli/move-file/-/move-file-2.0.0.tgz";
        sha512 = "UR6D5f4KEGWJV6BGPH3Qb2EtgH+t+1XQ1Tt85c7qicN6cezzuHPdZwwAxqZr4JLtnQu0LZsTza/5gmNmSl8XLg==";
      };
    };
    "@tootallnate/once-2.0.0" = {
      name = "_at_tootallnate_slash_once";
      packageName = "@tootallnate/once";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tootallnate/once/-/once-2.0.0.tgz";
        sha512 = "XCuKFP5PS55gnMVu3dty8KPatLqUoy/ZYzDzAGCQ8JNFCkLXzmI7vNHCR+XpbZaMWQK/vQubr7PkYq8g470J/A==";
      };
    };
    "@xmldom/xmldom-0.7.5" = {
      name = "_at_xmldom_slash_xmldom";
      packageName = "@xmldom/xmldom";
      version = "0.7.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@xmldom/xmldom/-/xmldom-0.7.5.tgz";
        sha512 = "V3BIhmY36fXZ1OtVcI9W+FxQqxVLsPKcNjWigIaa81dLC9IolJl5Mt4Cvhmr0flUnjSpTdrbMTSbXqYqV5dT6A==";
      };
    };
    "abbrev-1.1.1" = {
      name = "abbrev";
      packageName = "abbrev";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/abbrev/-/abbrev-1.1.1.tgz";
        sha512 = "nne9/IiQ/hzIhY6pdDnbBtz7DjPTKrY00P/zvPSm5pOFkl6xuGrGnXn/VtTNNfNtAfZ9/1RtehkszU9qcTii0Q==";
      };
    };
    "agent-base-6.0.2" = {
      name = "agent-base";
      packageName = "agent-base";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/agent-base/-/agent-base-6.0.2.tgz";
        sha512 = "RZNwNclF7+MS/8bDg70amg32dyeZGZxiDuQmZxKLAlQjr3jGyLx+4Kkk58UO7D2QdgFIQCovuSuZESne6RG6XQ==";
      };
    };
    "agentkeepalive-4.2.1" = {
      name = "agentkeepalive";
      packageName = "agentkeepalive";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/agentkeepalive/-/agentkeepalive-4.2.1.tgz";
        sha512 = "Zn4cw2NEqd+9fiSVWMscnjyQ1a8Yfoc5oBajLeo5w+YBHgDUcEBY2hS4YpTz6iN5f/2zQiktcuM6tS8x1p9dpA==";
      };
    };
    "aggregate-error-3.1.0" = {
      name = "aggregate-error";
      packageName = "aggregate-error";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aggregate-error/-/aggregate-error-3.1.0.tgz";
        sha512 = "4I7Td01quW/RpocfNayFdFVk1qSuoh0E7JrbRJ16nH01HhKFQ88INq9Sd+nd72zqRySlr9BmDA8xlEJ6vJMrYA==";
      };
    };
    "ansi-regex-5.0.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz";
        sha512 = "quJQXlTSUGL2LH9SUXo8VwsY4soanhgo6LNSm84E1LBcE8s3O0wpdiRzyR9z/ZZJMlMWv37qOOb9pdJlMUEKFQ==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "aproba-2.0.0" = {
      name = "aproba";
      packageName = "aproba";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aproba/-/aproba-2.0.0.tgz";
        sha512 = "lYe4Gx7QT+MKGbDsA+Z+he/Wtef0BiwDOlK/XkBrdfsh9J/jPPXbX0tE9x9cl27Tmu5gg3QUbUrQYa/y+KOHPQ==";
      };
    };
    "are-we-there-yet-3.0.0" = {
      name = "are-we-there-yet";
      packageName = "are-we-there-yet";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/are-we-there-yet/-/are-we-there-yet-3.0.0.tgz";
        sha512 = "0GWpv50YSOcLXaN6/FAKY3vfRbllXWV2xvfA/oKJF8pzFhWXPV+yjhJXDBbjscDYowv7Yw1A3uigpzn5iEGTyw==";
      };
    };
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
      };
    };
    "argparse-2.0.1" = {
      name = "argparse";
      packageName = "argparse";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-2.0.1.tgz";
        sha512 = "8+9WqebbFzpX9OR+Wa6O29asIogeRMzcGtAINdpMHHyAg10f05aSFVBbcEqGf/PXw1EjAZ+q2/bEBg3DvurK3Q==";
      };
    };
    "array-each-1.0.1" = {
      name = "array-each";
      packageName = "array-each";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-each/-/array-each-1.0.1.tgz";
        sha512 = "zHjL5SZa68hkKHBFBK6DJCTtr9sfTCPCaph/L7tMSLcTFgy+zX7E+6q5UArbtOtMBCtxdICpfTCspRse+ywyXA==";
      };
    };
    "array-slice-1.1.0" = {
      name = "array-slice";
      packageName = "array-slice";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-slice/-/array-slice-1.1.0.tgz";
        sha512 = "B1qMD3RBP7O8o0H2KbrXDyB0IccejMF15+87Lvlor12ONPRHP6gTjXMNkt/d3ZuOGbAe66hFmaCfECI24Ufp6w==";
      };
    };
    "async-3.2.3" = {
      name = "async";
      packageName = "async";
      version = "3.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-3.2.3.tgz";
        sha512 = "spZRyzKL5l5BZQrr/6m/SqFdBN0q3OCI0f9rjfBzCMBIP4p75P620rR3gTmaksNOhmzgdxcaxdNfMy6anrbM0g==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "bindings-1.5.0" = {
      name = "bindings";
      packageName = "bindings";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bindings/-/bindings-1.5.0.tgz";
        sha512 = "p2q/t/mhvuOj/UeLlV6566GD/guowlr0hHxClI0W9m7MWYkL1F0hLo+0Aexs9HSPCtR1SXQ0TD3MMKrXZajbiQ==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "brace-expansion-2.0.1" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-2.0.1.tgz";
        sha512 = "XnAIvQ8eM+kC6aULx6wuQiwVsnzsi9d3WxzV3FpWTGA19F621kwdbsAcFKXgKUHZWsy+mY6iL1sHTxWEFCytDA==";
      };
    };
    "braces-3.0.2" = {
      name = "braces";
      packageName = "braces";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-3.0.2.tgz";
        sha512 = "b8um+L1RzM3WDSzvhm6gIz1yfTbBt6YTlcEKAvsmqCZZFw46z626lVj9j1yEPW33H5H+lBQpZMP1k8l+78Ha0A==";
      };
    };
    "bufferstreams-3.0.0" = {
      name = "bufferstreams";
      packageName = "bufferstreams";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bufferstreams/-/bufferstreams-3.0.0.tgz";
        sha512 = "Qg0ggJUWJq90vtg4lDsGN9CDWvzBMQxhiEkSOD/sJfYt6BLect3eV1/S6K7SCSKJ34n60rf6U5eUPmQENVE4UA==";
      };
    };
    "cacache-16.1.0" = {
      name = "cacache";
      packageName = "cacache";
      version = "16.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cacache/-/cacache-16.1.0.tgz";
        sha512 = "Pk4aQkwCW82A4jGKFvcGkQFqZcMspfP9YWq9Pr87/ldDvlWf718zeI6KWCdKt/jeihu6BytHRUicJPB1K2k8EQ==";
      };
    };
    "chalk-4.1.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-4.1.2.tgz";
        sha512 = "oKnbhFyRIXpUuez8iBMmyEa4nbj4IOQyuhc/wy9kY7/WVPcwIO9VA668Pu8RkO7+0G76SLROeyw9CpQ061i4mA==";
      };
    };
    "chownr-2.0.0" = {
      name = "chownr";
      packageName = "chownr";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chownr/-/chownr-2.0.0.tgz";
        sha512 = "bIomtDF5KGpdogkLd9VspvFzk9KfpyyGlS8YFVZl7TGPBHL5snIOnxeshwVgPteQ9b4Eydl+pVbIyE1DcvCWgQ==";
      };
    };
    "clean-stack-2.2.0" = {
      name = "clean-stack";
      packageName = "clean-stack";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/clean-stack/-/clean-stack-2.2.0.tgz";
        sha512 = "4diC9HaTE+KRAMWhDhrGOECgWZxoevMc5TlkObMqNSsVU62PYzXZ/SMTjzyGAFF1YusgxGcSWTEXBhp0CPwQ1A==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "color-support-1.1.3" = {
      name = "color-support";
      packageName = "color-support";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-support/-/color-support-1.1.3.tgz";
        sha512 = "qiBjkpbMLO/HL68y+lh4q0/O1MZFj2RX6X/KmMa3+gJD3z+WwI1ZzDHysvqHGS3mP6mznPckpXmw1nI9cJjyRg==";
      };
    };
    "colors-1.1.2" = {
      name = "colors";
      packageName = "colors";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.1.2.tgz";
        sha1 = "168a4701756b6a7f51a12ce0c97bfa28c084ed63";
      };
    };
    "commander-7.2.0" = {
      name = "commander";
      packageName = "commander";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-7.2.0.tgz";
        sha512 = "QrWXB+ZQSVPmIWIhtEO9H+gwHaMGYiF5ChvoJ+K9ZGHG/sVsa6yiesAD1GC/x46sET00Xlwo1u49RVVVzvcSkw==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "console-control-strings-1.1.0" = {
      name = "console-control-strings";
      packageName = "console-control-strings";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/console-control-strings/-/console-control-strings-1.1.0.tgz";
        sha1 = "3d7cf4464db6446ea644bf4b39507f9851008e8e";
      };
    };
    "core-util-is-1.0.3" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.3.tgz";
        sha512 = "ZQBvi1DcpJ4GDqanjucZ2Hj3wEO5pZDS89BWbkcrvdxksJorwUDDZamX9ldFkp9aw2lmBDLgkObEA4DWNJ9FYQ==";
      };
    };
    "cubic2quad-1.2.1" = {
      name = "cubic2quad";
      packageName = "cubic2quad";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cubic2quad/-/cubic2quad-1.2.1.tgz";
        sha512 = "wT5Y7mO8abrV16gnssKdmIhIbA9wSkeMzhh27jAguKrV82i24wER0vL5TGhUJ9dbJNDcigoRZ0IAHFEEEI4THQ==";
      };
    };
    "dateformat-3.0.3" = {
      name = "dateformat";
      packageName = "dateformat";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/dateformat/-/dateformat-3.0.3.tgz";
        sha512 = "jyCETtSl3VMZMWeRo7iY1FL19ges1t55hMo5yaam4Jrsm5EPL89UQkoQRyiI+Yf4k8r2ZpdngkV8hr1lIdjb3Q==";
      };
    };
    "debug-4.3.4" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.4.tgz";
        sha512 = "PRWFHuSU3eDtQJPvnNY7Jcket1j0t5OuOsFzPPzsekD52Zl8qUfFIPEiswXqIvHWGVHOgX+7G/vCNNhehwxfkQ==";
      };
    };
    "delegates-1.0.0" = {
      name = "delegates";
      packageName = "delegates";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delegates/-/delegates-1.0.0.tgz";
        sha1 = "84c6e159b81904fdca59a0ef44cd870d31250f9a";
      };
    };
    "depd-1.1.2" = {
      name = "depd";
      packageName = "depd";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.1.2.tgz";
        sha1 = "9bcd52e14c097763e749b274c4346ed2e560b5a9";
      };
    };
    "detect-file-1.0.0" = {
      name = "detect-file";
      packageName = "detect-file";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/detect-file/-/detect-file-1.0.0.tgz";
        sha1 = "f0d66d03672a825cb1b73bdb3fe62310c8e552b7";
      };
    };
    "emoji-regex-8.0.0" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz";
        sha512 = "MSjYzcWNOA0ewAHpz0MxpYFvwg6yjy1NG3xteoqz644VCo/RPgnr1/GGt+ic3iJTzQ8Eu3TdM14SawnVUmGE6A==";
      };
    };
    "encoding-0.1.13" = {
      name = "encoding";
      packageName = "encoding";
      version = "0.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/encoding/-/encoding-0.1.13.tgz";
        sha512 = "ETBauow1T35Y/WZMkio9jiM0Z5xjHHmJ4XmjZOq1l/dXz3lr2sRn87nJy20RupqSh1F2m3HHPSp8ShIPQJrJ3A==";
      };
    };
    "env-paths-2.2.1" = {
      name = "env-paths";
      packageName = "env-paths";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/env-paths/-/env-paths-2.2.1.tgz";
        sha512 = "+h1lkLKhZMTYjog1VEpJNG7NZJWcuc2DDk/qsqSTRRCOXiLjeQ1d1/udrUGhqMxUgAlwKNZ0cf2uqan5GLuS2A==";
      };
    };
    "err-code-2.0.3" = {
      name = "err-code";
      packageName = "err-code";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/err-code/-/err-code-2.0.3.tgz";
        sha512 = "2bmlRpNKBxT/CRmPOlyISQpNj+qSeYvcym/uT0Jx2bMOlKLtSy1ZmLuVxSEKKyor/N5yhvp/ZiG1oE3DEYMSFA==";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "eventemitter2-0.4.14" = {
      name = "eventemitter2";
      packageName = "eventemitter2";
      version = "0.4.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter2/-/eventemitter2-0.4.14.tgz";
        sha1 = "8f61b75cde012b2e9eb284d4545583b5643b61ab";
      };
    };
    "exit-0.1.2" = {
      name = "exit";
      packageName = "exit";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/exit/-/exit-0.1.2.tgz";
        sha1 = "0632638f8d877cc82107d30a0fff1a17cba1cd0c";
      };
    };
    "expand-tilde-2.0.2" = {
      name = "expand-tilde";
      packageName = "expand-tilde";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/expand-tilde/-/expand-tilde-2.0.2.tgz";
        sha1 = "97e801aa052df02454de46b02bf621642cdc8502";
      };
    };
    "extend-3.0.2" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.2.tgz";
        sha512 = "fjquC59cD7CyW6urNXK0FBufkZcoiGG80wTuPujX590cB5Ttln20E2UB4S/WARVqhXffZl2LNgS+gQdPIIim/g==";
      };
    };
    "file-uri-to-path-1.0.0" = {
      name = "file-uri-to-path";
      packageName = "file-uri-to-path";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-uri-to-path/-/file-uri-to-path-1.0.0.tgz";
        sha512 = "0Zt+s3L7Vf1biwWZ29aARiVYLx7iMGnEUl9x33fbB/j3jR81u/O2LbqK+Bm1CDSNDKVtJ/YjwY7TUd5SkeLQLw==";
      };
    };
    "fill-range-7.0.1" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-7.0.1.tgz";
        sha512 = "qOo9F+dMUmC2Lcb4BbVvnKJxTPjCm+RRpe4gDuGrzkL7mEVl/djYSu2OdQ2Pa302N4oqkSg9ir6jaLWJ2USVpQ==";
      };
    };
    "findup-sync-0.3.0" = {
      name = "findup-sync";
      packageName = "findup-sync";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/findup-sync/-/findup-sync-0.3.0.tgz";
        sha1 = "37930aa5d816b777c03445e1966cc6790a4c0b16";
      };
    };
    "findup-sync-4.0.0" = {
      name = "findup-sync";
      packageName = "findup-sync";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/findup-sync/-/findup-sync-4.0.0.tgz";
        sha512 = "6jvvn/12IC4quLBL1KNokxC7wWTvYncaVUYSoxWw7YykPLuRrnv4qdHcSOywOI5RpkOVGeQRtWM8/q+G6W6qfQ==";
      };
    };
    "fined-1.2.0" = {
      name = "fined";
      packageName = "fined";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fined/-/fined-1.2.0.tgz";
        sha512 = "ZYDqPLGxDkDhDZBjZBb+oD1+j0rA4E0pXY50eplAAOPg2N/gUBSSk5IM1/QhPfyVo19lJ+CvXpqfvk+b2p/8Ng==";
      };
    };
    "flagged-respawn-1.0.1" = {
      name = "flagged-respawn";
      packageName = "flagged-respawn";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/flagged-respawn/-/flagged-respawn-1.0.1.tgz";
        sha512 = "lNaHNVymajmk0OJMBn8fVUAU1BtDeKIqKoVhk4xAALB57aALg6b4W0MfJ/cUE0g9YBXy5XhSlPIpYIJ7HaY/3Q==";
      };
    };
    "for-in-1.0.2" = {
      name = "for-in";
      packageName = "for-in";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/for-in/-/for-in-1.0.2.tgz";
        sha1 = "81068d295a8142ec0ac726c6e2200c30fb6d5e80";
      };
    };
    "for-own-1.0.0" = {
      name = "for-own";
      packageName = "for-own";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/for-own/-/for-own-1.0.0.tgz";
        sha1 = "c63332f415cedc4b04dbfe70cf836494c53cb44b";
      };
    };
    "fs-minipass-2.1.0" = {
      name = "fs-minipass";
      packageName = "fs-minipass";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-minipass/-/fs-minipass-2.1.0.tgz";
        sha512 = "V/JgOLFCS+R6Vcq0slCuaeWEdNC3ouDlJMNIsacH2VtALiu9mV4LPrHc5cDl8k5aw6J8jwgWWpiTo5RYhmIzvg==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "gauge-4.0.4" = {
      name = "gauge";
      packageName = "gauge";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/gauge/-/gauge-4.0.4.tgz";
        sha512 = "f9m+BEN5jkg6a0fZjleidjN51VE1X+mPFQ2DJ0uv1V39oCLCbsGe6yjbBnp7eK7z/+GAon99a3nHuqbuuthyPg==";
      };
    };
    "geometry-interfaces-1.1.4" = {
      name = "geometry-interfaces";
      packageName = "geometry-interfaces";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/geometry-interfaces/-/geometry-interfaces-1.1.4.tgz";
        sha512 = "qD6OdkT6NcES9l4Xx3auTpwraQruU7dARbQPVO71MKvkGYw5/z/oIiGymuFXrRaEQa5Y67EIojUpaLeGEa5hGA==";
      };
    };
    "getobject-1.0.2" = {
      name = "getobject";
      packageName = "getobject";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/getobject/-/getobject-1.0.2.tgz";
        sha512 = "2zblDBaFcb3rB4rF77XVnuINOE2h2k/OnqXAiy0IrTxUfV1iFp3la33oAQVY9pCpWU268WFYVt2t71hlMuLsOg==";
      };
    };
    "glob-5.0.15" = {
      name = "glob";
      packageName = "glob";
      version = "5.0.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-5.0.15.tgz";
        sha1 = "1bc936b9e02f4a603fcc222ecf7633d30b8b93b1";
      };
    };
    "glob-7.1.7" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.7.tgz";
        sha512 = "OvD9ENzPLbegENnYP5UUfJIirTg4+XwMWGaQfQTY0JenxNvvIKP3U3/tAQSPIu/lHxXYSZmpXlUHeqAIdKzBLQ==";
      };
    };
    "glob-8.0.3" = {
      name = "glob";
      packageName = "glob";
      version = "8.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-8.0.3.tgz";
        sha512 = "ull455NHSHI/Y1FqGaaYFaLGkNMMJbavMrEGFXG/PGrg6y7sutWHUHrz6gy6WEBH6akM1M414dWKCNs+IhKdiQ==";
      };
    };
    "global-modules-1.0.0" = {
      name = "global-modules";
      packageName = "global-modules";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/global-modules/-/global-modules-1.0.0.tgz";
        sha512 = "sKzpEkf11GpOFuw0Zzjzmt4B4UZwjOcG757PPvrfhxcLFbq0wpsgpOqxpxtxFiCG4DtG93M6XRVbF2oGdev7bg==";
      };
    };
    "global-prefix-1.0.2" = {
      name = "global-prefix";
      packageName = "global-prefix";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/global-prefix/-/global-prefix-1.0.2.tgz";
        sha1 = "dbf743c6c14992593c655568cb66ed32c0122ebe";
      };
    };
    "graceful-fs-4.2.10" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.10.tgz";
        sha512 = "9ByhssR2fPVsNZj478qUUbKfmL0+t5BDVyjShtyZZLiK7ZDAArFFfopyOTj0M05wE2tJPisA4iTnnXl2YoPvOA==";
      };
    };
    "grunt-1.5.3" = {
      name = "grunt";
      packageName = "grunt";
      version = "1.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt/-/grunt-1.5.3.tgz";
        sha512 = "mKwmo4X2d8/4c/BmcOETHek675uOqw0RuA/zy12jaspWqvTp4+ZeQF1W+OTpcbncnaBsfbQJ6l0l4j+Sn/GmaQ==";
      };
    };
    "grunt-cli-1.4.3" = {
      name = "grunt-cli";
      packageName = "grunt-cli";
      version = "1.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-cli/-/grunt-cli-1.4.3.tgz";
        sha512 = "9Dtx/AhVeB4LYzsViCjUQkd0Kw0McN2gYpdmGYKtE2a5Yt7v1Q+HYZVWhqXc/kGnxlMtqKDxSwotiGeFmkrCoQ==";
      };
    };
    "grunt-known-options-2.0.0" = {
      name = "grunt-known-options";
      packageName = "grunt-known-options";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-known-options/-/grunt-known-options-2.0.0.tgz";
        sha512 = "GD7cTz0I4SAede1/+pAbmJRG44zFLPipVtdL9o3vqx9IEyb7b4/Y3s7r6ofI3CchR5GvYJ+8buCSioDv5dQLiA==";
      };
    };
    "grunt-legacy-log-3.0.0" = {
      name = "grunt-legacy-log";
      packageName = "grunt-legacy-log";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-legacy-log/-/grunt-legacy-log-3.0.0.tgz";
        sha512 = "GHZQzZmhyq0u3hr7aHW4qUH0xDzwp2YXldLPZTCjlOeGscAOWWPftZG3XioW8MasGp+OBRIu39LFx14SLjXRcA==";
      };
    };
    "grunt-legacy-log-utils-2.1.0" = {
      name = "grunt-legacy-log-utils";
      packageName = "grunt-legacy-log-utils";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-legacy-log-utils/-/grunt-legacy-log-utils-2.1.0.tgz";
        sha512 = "lwquaPXJtKQk0rUM1IQAop5noEpwFqOXasVoedLeNzaibf/OPWjKYvvdqnEHNmU+0T0CaReAXIbGo747ZD+Aaw==";
      };
    };
    "grunt-legacy-util-2.0.1" = {
      name = "grunt-legacy-util";
      packageName = "grunt-legacy-util";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-legacy-util/-/grunt-legacy-util-2.0.1.tgz";
        sha512 = "2bQiD4fzXqX8rhNdXkAywCadeqiPiay0oQny77wA2F3WF4grPJXCvAcyoWUJV+po/b15glGkxuSiQCK299UC2w==";
      };
    };
    "grunt-webfonts-4.0.1" = {
      name = "grunt-webfonts";
      packageName = "grunt-webfonts";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-webfonts/-/grunt-webfonts-4.0.1.tgz";
        sha512 = "wfRInj5cBmic+/K49qYcMMcUsvqkLUrtiKaMkIieXpHa5pR8R7fDeMTm/tcT438AcQy4SFBAJZAEKGBsFYF7SA==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "has-unicode-2.0.1" = {
      name = "has-unicode";
      packageName = "has-unicode";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-unicode/-/has-unicode-2.0.1.tgz";
        sha1 = "e0e6fe6a28cf51138855e086d1691e771de2a8b9";
      };
    };
    "homedir-polyfill-1.0.3" = {
      name = "homedir-polyfill";
      packageName = "homedir-polyfill";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/homedir-polyfill/-/homedir-polyfill-1.0.3.tgz";
        sha512 = "eSmmWE5bZTK2Nou4g0AI3zZ9rswp7GRKoKXS1BLUkvPviOqs4YTN1djQIqrXy9k5gEtdLPy86JjRwsNM9tnDcA==";
      };
    };
    "hooker-0.2.3" = {
      name = "hooker";
      packageName = "hooker";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hooker/-/hooker-0.2.3.tgz";
        sha1 = "b834f723cc4a242aa65963459df6d984c5d3d959";
      };
    };
    "http-cache-semantics-4.1.0" = {
      name = "http-cache-semantics";
      packageName = "http-cache-semantics";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-cache-semantics/-/http-cache-semantics-4.1.0.tgz";
        sha512 = "carPklcUh7ROWRK7Cv27RPtdhYhUsela/ue5/jKzjegVvXDqM2ILE9Q2BGn9JZJh1g87cp56su/FgQSzcWS8cQ==";
      };
    };
    "http-proxy-agent-5.0.0" = {
      name = "http-proxy-agent";
      packageName = "http-proxy-agent";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-proxy-agent/-/http-proxy-agent-5.0.0.tgz";
        sha512 = "n2hY8YdoRE1i7r6M0w9DIw5GgZN0G25P8zLCRQ8rjXtTU3vsNFBI/vWK/UIeE6g5MUUz6avwAPXmL6Fy9D/90w==";
      };
    };
    "https-proxy-agent-5.0.1" = {
      name = "https-proxy-agent";
      packageName = "https-proxy-agent";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/https-proxy-agent/-/https-proxy-agent-5.0.1.tgz";
        sha512 = "dFcAjpTQFgoLMzC2VwU+C/CbS7uRL0lWmxDITmqm7C+7F0Odmj6s9l6alZc6AELXhrnggM2CeWSXHGOdX2YtwA==";
      };
    };
    "humanize-ms-1.2.1" = {
      name = "humanize-ms";
      packageName = "humanize-ms";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/humanize-ms/-/humanize-ms-1.2.1.tgz";
        sha1 = "c46e3159a293f6b896da29316d8b6fe8bb79bbed";
      };
    };
    "iconv-lite-0.4.24" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.24";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.24.tgz";
        sha512 = "v3MXnZAcvnywkTUEZomIActle7RXXeedOR31wwl7VlyoXO4Qi9arvSenNQWne1TcRwhCL1HwLI21bEqdpj8/rA==";
      };
    };
    "iconv-lite-0.6.3" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.3.tgz";
        sha512 = "4fCk79wshMdzMp2rH06qWrJE4iolqLhCUH+OiuIgU++RB0+94NlDL81atO7GX55uUKueo0txHNtvEyI6D7WdMw==";
      };
    };
    "imurmurhash-0.1.4" = {
      name = "imurmurhash";
      packageName = "imurmurhash";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/imurmurhash/-/imurmurhash-0.1.4.tgz";
        sha1 = "9218b9b2b928a238b13dc4fb6b6d576f231453ea";
      };
    };
    "indent-string-4.0.0" = {
      name = "indent-string";
      packageName = "indent-string";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/indent-string/-/indent-string-4.0.0.tgz";
        sha512 = "EdDDZu4A2OyIK7Lr/2zG+w5jmbuk1DVBnEwREQvBzspBJkCEbRa8GxU1lghYcaGJCnRWibjDXlq779X1/y5xwg==";
      };
    };
    "infer-owner-1.0.4" = {
      name = "infer-owner";
      packageName = "infer-owner";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/infer-owner/-/infer-owner-1.0.4.tgz";
        sha512 = "IClj+Xz94+d7irH5qRyfJonOdfTzuDaifE6ZPWfx0N0+/ATZCbuTPq2prFl526urkQd90WyUKIh1DfBQ2hMz9A==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "ini-1.3.8" = {
      name = "ini";
      packageName = "ini";
      version = "1.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-1.3.8.tgz";
        sha512 = "JV/yugV2uzW5iMRSiZAyDtQd+nxtUnjeLt0acNdw98kKLrvuRVyB80tsREOE7yvGVgalhZ6RNXCmEHkUKBKxew==";
      };
    };
    "interpret-1.1.0" = {
      name = "interpret";
      packageName = "interpret";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/interpret/-/interpret-1.1.0.tgz";
        sha1 = "7ed1b1410c6a0e0f78cf95d3b8440c63f78b8614";
      };
    };
    "ip-1.1.8" = {
      name = "ip";
      packageName = "ip";
      version = "1.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ip/-/ip-1.1.8.tgz";
        sha512 = "PuExPYUiu6qMBQb4l06ecm6T6ujzhmh+MeJcW9wa89PoAz5pvd4zPgN5WJV104mb6S2T1AwNIAaB70JNrLQWhg==";
      };
    };
    "is-absolute-1.0.0" = {
      name = "is-absolute";
      packageName = "is-absolute";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-absolute/-/is-absolute-1.0.0.tgz";
        sha512 = "dOWoqflvcydARa360Gvv18DZ/gRuHKi2NU/wU5X1ZFzdYfH29nkiNZsF3mp4OJ3H4yo9Mx8A/uAGNzpzPN3yBA==";
      };
    };
    "is-core-module-2.9.0" = {
      name = "is-core-module";
      packageName = "is-core-module";
      version = "2.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-core-module/-/is-core-module-2.9.0.tgz";
        sha512 = "+5FPy5PnwmO3lvfMb0AsoPaBG+5KHUI0wYFXOtYPnVVVspTFUuMZNfNaNVRt3FZadstu2c8x23vykRW/NBoU6A==";
      };
    };
    "is-extglob-2.1.1" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
        sha1 = "a88c02535791f02ed37c76a1b9ea9773c833f8c2";
      };
    };
    "is-fullwidth-code-point-3.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz";
        sha512 = "zymm5+u+sCsSWyD9qNaejV3DFvhCKclKdizYaJUuHA83RLjb7nSuGnddCHGv0hk+KY7BMAlsWeK4Ueg6EV6XQg==";
      };
    };
    "is-glob-4.0.3" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.3.tgz";
        sha512 = "xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==";
      };
    };
    "is-lambda-1.0.1" = {
      name = "is-lambda";
      packageName = "is-lambda";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-lambda/-/is-lambda-1.0.1.tgz";
        sha1 = "3d9877899e6a53efc0160504cde15f82e6f061d5";
      };
    };
    "is-number-7.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz";
        sha512 = "41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==";
      };
    };
    "is-plain-object-2.0.4" = {
      name = "is-plain-object";
      packageName = "is-plain-object";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-plain-object/-/is-plain-object-2.0.4.tgz";
        sha512 = "h5PpgXkWitc38BBMYawTYMWJHFZJVnBquFE57xFpjB8pJFiF6gZ+bU+WyI/yqXiFR5mdLsgYNaPe8uao6Uv9Og==";
      };
    };
    "is-relative-1.0.0" = {
      name = "is-relative";
      packageName = "is-relative";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-relative/-/is-relative-1.0.0.tgz";
        sha512 = "Kw/ReK0iqwKeu0MITLFuj0jbPAmEiOsIwyIXvvbfa6QfmN9pkD1M+8pdk7Rl/dTKbH34/XBFMbgD4iMJhLQbGA==";
      };
    };
    "is-unc-path-1.0.0" = {
      name = "is-unc-path";
      packageName = "is-unc-path";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-unc-path/-/is-unc-path-1.0.0.tgz";
        sha512 = "mrGpVd0fs7WWLfVsStvgF6iEJnbjDFZh9/emhRDcGWTduTfNHd9CHeUwH3gYIjdbwo4On6hunkztwOaAw0yllQ==";
      };
    };
    "is-windows-1.0.2" = {
      name = "is-windows";
      packageName = "is-windows";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-windows/-/is-windows-1.0.2.tgz";
        sha512 = "eXK1UInq2bPmjyX6e3VHIzMLobc4J94i4AWn+Hpq3OU5KkrRC96OAcR3PRJ/pGu6m8TRnBHP9dkXQVsT/COVIA==";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha1 = "e8fbf374dc556ff8947a10dcb0572d633f2cfa10";
      };
    };
    "isobject-3.0.1" = {
      name = "isobject";
      packageName = "isobject";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isobject/-/isobject-3.0.1.tgz";
        sha1 = "4e431e92b11a9731636aa1f9c8d1ccbcfdab78df";
      };
    };
    "js-yaml-3.14.1" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.14.1.tgz";
        sha512 = "okMH7OXXJ7YrN9Ok3/SXrnu4iX9yOk+25nqX4imS2npuvTYDmo/QEZoqwZkYaIDk3jVvBOTOIEgEhaLOynBS9g==";
      };
    };
    "kind-of-6.0.3" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "6.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-6.0.3.tgz";
        sha512 = "dcS1ul+9tmeD95T+x28/ehLgd9mENa3LsvDTtzm3vyBEO7RPptvAD+t44WVXaUjTBRcrpFeFlC8WCruUR456hw==";
      };
    };
    "liftup-3.0.1" = {
      name = "liftup";
      packageName = "liftup";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/liftup/-/liftup-3.0.1.tgz";
        sha512 = "yRHaiQDizWSzoXk3APcA71eOI/UuhEkNN9DiW2Tt44mhYzX4joFoCZlxsSOF7RyeLlfqzFLQI1ngFq3ggMPhOw==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "lru-cache-7.10.1" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "7.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-7.10.1.tgz";
        sha512 = "BQuhQxPuRl79J5zSXRP+uNzPOyZw2oFI9JLRQ80XswSvg21KMKNtQza9eF42rfI/3Z40RvzBdXgziEkudzjo8A==";
      };
    };
    "make-fetch-happen-10.1.5" = {
      name = "make-fetch-happen";
      packageName = "make-fetch-happen";
      version = "10.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/make-fetch-happen/-/make-fetch-happen-10.1.5.tgz";
        sha512 = "mucOj2H0Jn/ax7H9K9T1bf0p1nn/mBFa551Os7ed9xRfLEx20aZhZeLslmRYfAaAqXZUGipcs+m5KOKvOH0XKA==";
      };
    };
    "make-iterator-1.0.1" = {
      name = "make-iterator";
      packageName = "make-iterator";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/make-iterator/-/make-iterator-1.0.1.tgz";
        sha512 = "pxiuXh0iVEq7VM7KMIhs5gxsfxCux2URptUQaXo4iZZJxBAzTPOLE2BumO5dbfVYq/hBJFBR/a1mFDmOx5AGmw==";
      };
    };
    "map-cache-0.2.2" = {
      name = "map-cache";
      packageName = "map-cache";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/map-cache/-/map-cache-0.2.2.tgz";
        sha1 = "c32abd0bd6525d9b051645bb4f26ac5dc98a0dbf";
      };
    };
    "memorystream-0.3.1" = {
      name = "memorystream";
      packageName = "memorystream";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/memorystream/-/memorystream-0.3.1.tgz";
        sha1 = "86d7090b30ce455d63fbae12dda51a47ddcaf9b2";
      };
    };
    "microbuffer-1.0.0" = {
      name = "microbuffer";
      packageName = "microbuffer";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/microbuffer/-/microbuffer-1.0.0.tgz";
        sha1 = "8b3832ed40c87d51f47bb234913a698a756d19d2";
      };
    };
    "micromatch-4.0.5" = {
      name = "micromatch";
      packageName = "micromatch";
      version = "4.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromatch/-/micromatch-4.0.5.tgz";
        sha512 = "DMy+ERcEW2q8Z2Po+WNXuw3c5YaUSFjAO5GsJqfEl7UjvtIuFKO6ZrKvcItdy98dwFI2N1tg3zNIdKaQT+aNdA==";
      };
    };
    "minimatch-3.0.8" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.8.tgz";
        sha512 = "6FsRAQsxQ61mw+qP1ZzbL9Bc78x2p5OqNgNpnoAFLTrX8n5Kxph0CsnhmKKNXTWjXqU5L0pGPR7hYk+XWZr60Q==";
      };
    };
    "minimatch-5.1.0" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-5.1.0.tgz";
        sha512 = "9TPBGGak4nHfGZsPBohm9AWg6NoT7QTCehS3BIJABslyZbzxfV78QM2Y6+i741OPZIafFAaiiEMh5OyIrJPgtg==";
      };
    };
    "minimist-1.2.6" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.6.tgz";
        sha512 = "Jsjnk4bw3YJqYzbdyBiNsPWHPfO++UGG749Cxs6peCu5Xg4nrena6OVxOYxrQTqww0Jmwt+Ref8rggumkTLz9Q==";
      };
    };
    "minipass-3.1.6" = {
      name = "minipass";
      packageName = "minipass";
      version = "3.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/minipass/-/minipass-3.1.6.tgz";
        sha512 = "rty5kpw9/z8SX9dmxblFA6edItUmwJgMeYDZRrwlIVN27i8gysGbznJwUggw2V/FVqFSDdWy040ZPS811DYAqQ==";
      };
    };
    "minipass-collect-1.0.2" = {
      name = "minipass-collect";
      packageName = "minipass-collect";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minipass-collect/-/minipass-collect-1.0.2.tgz";
        sha512 = "6T6lH0H8OG9kITm/Jm6tdooIbogG9e0tLgpY6mphXSm/A9u8Nq1ryBG+Qspiub9LjWlBPsPS3tWQ/Botq4FdxA==";
      };
    };
    "minipass-fetch-2.1.0" = {
      name = "minipass-fetch";
      packageName = "minipass-fetch";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minipass-fetch/-/minipass-fetch-2.1.0.tgz";
        sha512 = "H9U4UVBGXEyyWJnqYDCLp1PwD8XIkJ4akNHp1aGVI+2Ym7wQMlxDKi4IB4JbmyU+pl9pEs/cVrK6cOuvmbK4Sg==";
      };
    };
    "minipass-flush-1.0.5" = {
      name = "minipass-flush";
      packageName = "minipass-flush";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/minipass-flush/-/minipass-flush-1.0.5.tgz";
        sha512 = "JmQSYYpPUqX5Jyn1mXaRwOda1uQ8HP5KAT/oDSLCzt1BYRhQU0/hDtsB1ufZfEEzMZ9aAVmsBw8+FWsIXlClWw==";
      };
    };
    "minipass-pipeline-1.2.4" = {
      name = "minipass-pipeline";
      packageName = "minipass-pipeline";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minipass-pipeline/-/minipass-pipeline-1.2.4.tgz";
        sha512 = "xuIq7cIOt09RPRJ19gdi4b+RiNvDFYe5JH+ggNvBqGqpQXcru3PcRmOZuHBKWK1Txf9+cQ+HMVN4d6z46LZP7A==";
      };
    };
    "minipass-sized-1.0.3" = {
      name = "minipass-sized";
      packageName = "minipass-sized";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/minipass-sized/-/minipass-sized-1.0.3.tgz";
        sha512 = "MbkQQ2CTiBMlA2Dm/5cY+9SWFEN8pzzOXi6rlM5Xxq0Yqbda5ZQy9sU75a673FE9ZK0Zsbr6Y5iP6u9nktfg2g==";
      };
    };
    "minizlib-2.1.2" = {
      name = "minizlib";
      packageName = "minizlib";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minizlib/-/minizlib-2.1.2.tgz";
        sha512 = "bAxsR8BVfj60DWXHE3u30oHzfl4G7khkSuPW+qvpd7jFRHm7dLxOjUk1EHACJ/hxLY8phGJ0YhYHZo7jil7Qdg==";
      };
    };
    "mkdirp-0.5.6" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.6.tgz";
        sha512 = "FP+p8RB8OWpF3YZBCrP5gtADmtXApB5AMLn+vdyA+PyxCjrCs00mjyUozssO33cwDeT3wNGdLxJ5M//YqtHAJw==";
      };
    };
    "mkdirp-1.0.4" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-1.0.4.tgz";
        sha512 = "vVqVZQyf3WLx2Shd0qJ9xuvqgAyKPLAiqITEtqW0oIUjzo3PePDd6fW9iFz30ef7Ysp/oiWqbhszeGWW2T6Gzw==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "nan-2.16.0" = {
      name = "nan";
      packageName = "nan";
      version = "2.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.16.0.tgz";
        sha512 = "UdAqHyFngu7TfQKsCBgAA6pWDkT8MAO7d0jyOecVhN5354xbLqdn8mV9Tat9gepAupm0bt2DbeaSC8vS52MuFA==";
      };
    };
    "neatequal-1.0.0" = {
      name = "neatequal";
      packageName = "neatequal";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/neatequal/-/neatequal-1.0.0.tgz";
        sha1 = "2ee1211bc9fa6e4c55715fd210bb05602eb1ae3b";
      };
    };
    "negotiator-0.6.3" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.6.3.tgz";
        sha512 = "+EUsqGPLsM+j/zdChZjsnX51g4XrHFOIXwfnCVPGlQk/k5giakcKsuxCObBRu6DSm9opw/O6slWbJdghQM4bBg==";
      };
    };
    "node-gyp-9.0.0" = {
      name = "node-gyp";
      packageName = "node-gyp";
      version = "9.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-gyp/-/node-gyp-9.0.0.tgz";
        sha512 = "Ma6p4s+XCTPxCuAMrOA/IJRmVy16R8Sdhtwl4PrCr7IBlj4cPawF0vg/l7nOT1jPbuNS7lIRJpBSvVsXwEZuzw==";
      };
    };
    "nopt-3.0.6" = {
      name = "nopt";
      packageName = "nopt";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-3.0.6.tgz";
        sha1 = "c6465dbf08abcd4db359317f79ac68a646b28ff9";
      };
    };
    "nopt-4.0.3" = {
      name = "nopt";
      packageName = "nopt";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-4.0.3.tgz";
        sha512 = "CvaGwVMztSMJLOeXPrez7fyfObdZqNUK1cPAEzLHrTybIua9pMdmmPR5YwtfNftIOMv3DPUhFaxsZMNTQO20Kg==";
      };
    };
    "nopt-5.0.0" = {
      name = "nopt";
      packageName = "nopt";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-5.0.0.tgz";
        sha512 = "Tbj67rffqceeLpcRXrT7vKAN8CwfPeIBgM7E6iBkmKLV7bEMwpGgYLGv0jACUsECaa/vuxP0IjEont6umdMgtQ==";
      };
    };
    "npmlog-6.0.2" = {
      name = "npmlog";
      packageName = "npmlog";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/npmlog/-/npmlog-6.0.2.tgz";
        sha512 = "/vBvz5Jfr9dT/aFWd0FIRf+T/Q2WBsLENygUaFUqstqsycmZAP/t5BvFJTK0viFmSUxiUKTUplWy5vt+rvKIxg==";
      };
    };
    "object.defaults-1.1.0" = {
      name = "object.defaults";
      packageName = "object.defaults";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.defaults/-/object.defaults-1.1.0.tgz";
        sha1 = "3a7f868334b407dea06da16d88d5cd29e435fecf";
      };
    };
    "object.map-1.0.1" = {
      name = "object.map";
      packageName = "object.map";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.map/-/object.map-1.0.1.tgz";
        sha1 = "cf83e59dc8fcc0ad5f4250e1f78b3b81bd801d37";
      };
    };
    "object.pick-1.3.0" = {
      name = "object.pick";
      packageName = "object.pick";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.pick/-/object.pick-1.3.0.tgz";
        sha1 = "87a10ac4c1694bd2e1cbf53591a66141fb5dd747";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "os-homedir-1.0.2" = {
      name = "os-homedir";
      packageName = "os-homedir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-homedir/-/os-homedir-1.0.2.tgz";
        sha1 = "ffbc4988336e0e833de0c168c7ef152121aa7fb3";
      };
    };
    "os-tmpdir-1.0.2" = {
      name = "os-tmpdir";
      packageName = "os-tmpdir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-tmpdir/-/os-tmpdir-1.0.2.tgz";
        sha1 = "bbe67406c79aa85c5cfec766fe5734555dfa1274";
      };
    };
    "osenv-0.1.5" = {
      name = "osenv";
      packageName = "osenv";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/osenv/-/osenv-0.1.5.tgz";
        sha512 = "0CWcCECdMVc2Rw3U5w9ZjqX6ga6ubk1xDVKxtBQPK7wis/0F2r9T6k4ydGYhecl7YUBxBVxhL5oisPsNxAPe2g==";
      };
    };
    "p-map-4.0.0" = {
      name = "p-map";
      packageName = "p-map";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-map/-/p-map-4.0.0.tgz";
        sha512 = "/bjOqmgETBYB5BoEeGVea8dmvHb2m9GLy1E9W43yeyfP6QQCZGFNa+XRceJEuDB6zqr+gKpIAmlLebMpykw/MQ==";
      };
    };
    "pako-1.0.11" = {
      name = "pako";
      packageName = "pako";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/pako/-/pako-1.0.11.tgz";
        sha512 = "4hLB8Py4zZce5s4yd9XzopqwVv/yGNhV1Bl8NTmCq1763HeK2+EwVTv+leGeL13Dnh2wfbqowVPXCIO0z4taYw==";
      };
    };
    "parse-filepath-1.0.2" = {
      name = "parse-filepath";
      packageName = "parse-filepath";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-filepath/-/parse-filepath-1.0.2.tgz";
        sha1 = "a632127f53aaf3d15876f5872f3ffac763d6c891";
      };
    };
    "parse-passwd-1.0.0" = {
      name = "parse-passwd";
      packageName = "parse-passwd";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-passwd/-/parse-passwd-1.0.0.tgz";
        sha1 = "6d5b934a456993b23d37f40a382d6f1666a8e5c6";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "path-parse-1.0.7" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.7.tgz";
        sha512 = "LDJzPVEEEPR+y48z93A0Ed0yXb8pAByGWo/k5YYdYgpY2/2EsOsksJrq7lOHxryrVOn1ejG6oAp8ahvOIQD8sw==";
      };
    };
    "path-root-0.1.1" = {
      name = "path-root";
      packageName = "path-root";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-root/-/path-root-0.1.1.tgz";
        sha1 = "9a4a6814cac1c0cd73360a95f32083c8ea4745b7";
      };
    };
    "path-root-regex-0.1.2" = {
      name = "path-root-regex";
      packageName = "path-root-regex";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-root-regex/-/path-root-regex-0.1.2.tgz";
        sha1 = "bfccdc8df5b12dc52c8b43ec38d18d72c04ba96d";
      };
    };
    "picomatch-2.3.1" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.1.tgz";
        sha512 = "JU3teHTNjmE2VCGFzuY8EXzCDVwEqB2a8fsIvwaStHhAWJEeVd1o1QD80CU6+ZdEXXSLbSsuLwJjkCBWqRQUVA==";
      };
    };
    "promise-inflight-1.0.1" = {
      name = "promise-inflight";
      packageName = "promise-inflight";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/promise-inflight/-/promise-inflight-1.0.1.tgz";
        sha1 = "98472870bf228132fcbdd868129bad12c3c029e3";
      };
    };
    "promise-retry-2.0.1" = {
      name = "promise-retry";
      packageName = "promise-retry";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/promise-retry/-/promise-retry-2.0.1.tgz";
        sha512 = "y+WKFlBR8BGXnsNlIHFGPZmyDf3DFMoLhaflAnyZgV6rG6xu+JwesTo2Q9R6XwYmtmwAFCkAk3e35jEdoeh/3g==";
      };
    };
    "readable-stream-1.1.14" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.1.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-1.1.14.tgz";
        sha1 = "7cf4c54ef648e3813084c636dd2079e166c081d9";
      };
    };
    "readable-stream-3.6.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.0.tgz";
        sha512 = "BViHy7LKeTz4oNnkcLJ+lVSL6vpiFeX6/d3oSH8zCW7UxP2onchk+vTGB143xuFjHS3deTgkKoXXymXqymiIdA==";
      };
    };
    "rechoir-0.7.1" = {
      name = "rechoir";
      packageName = "rechoir";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/rechoir/-/rechoir-0.7.1.tgz";
        sha512 = "/njmZ8s1wVeR6pjTZ+0nCnv8SpZNRMT2D1RLOJQESlYFDBvwpTA4KWJpZ+sBJ4+vhjILRcK7JIFdGCdxEAAitg==";
      };
    };
    "resolve-1.22.0" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.22.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.22.0.tgz";
        sha512 = "Hhtrw0nLeSrFQ7phPp4OOcVjLPIeMnRlr5mcnVuMe7M/7eBn98A3hmFRLoFo3DLZkivSYwhRUJTyPyWAk56WLw==";
      };
    };
    "resolve-dir-1.0.1" = {
      name = "resolve-dir";
      packageName = "resolve-dir";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-dir/-/resolve-dir-1.0.1.tgz";
        sha1 = "79a40644c362be82f26effe739c9bb5382046f43";
      };
    };
    "retry-0.12.0" = {
      name = "retry";
      packageName = "retry";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/retry/-/retry-0.12.0.tgz";
        sha1 = "1b42a6266a21f07421d1b0b54b7dc167b01c013b";
      };
    };
    "rimraf-2.6.3" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.6.3.tgz";
        sha512 = "mwqeW5XsA2qAejG46gYdENaxXjx9onRNCfn7L0duuP4hCuTIi/QO7PDK07KJfp1d+izWPrzEJDcSqBa0OZQriA==";
      };
    };
    "rimraf-3.0.2" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-3.0.2.tgz";
        sha512 = "JZkJMZkAGFFPP2YqXZXPbMlMBgsxzE8ILs4lMIX/2o0L9UBw9O/Y3o6wFw/i9YLapcUJWwqbi3kdxIPdC62TIA==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "sax-1.2.4" = {
      name = "sax";
      packageName = "sax";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.2.4.tgz";
        sha512 = "NqVDv9TpANUjFm0N8uM5GxL36UgKi9/atZw+x7YFnQ8ckwFGKrl4xX4yWtrey3UJm5nP1kUbnYgLopqWNSRhWw==";
      };
    };
    "semver-7.3.7" = {
      name = "semver";
      packageName = "semver";
      version = "7.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.3.7.tgz";
        sha512 = "QlYTucUYOews+WeEujDoEGziz4K6c47V/Bd+LjSSYcA94p+DmINdf7ncaUinThfvZyu13lN9OY1XDxt8C0Tw0g==";
      };
    };
    "set-blocking-2.0.0" = {
      name = "set-blocking";
      packageName = "set-blocking";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-blocking/-/set-blocking-2.0.0.tgz";
        sha1 = "045f9782d011ae9a6803ddd382b24392b3d890f7";
      };
    };
    "signal-exit-3.0.7" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.7.tgz";
        sha512 = "wnD2ZE+l+SPC/uoS0vXeE9L1+0wuaMqKlfz9AMUo38JsyLSBWSFcHR1Rri62LZc12vLr1gb3jl7iwQhgwpAbGQ==";
      };
    };
    "smart-buffer-4.2.0" = {
      name = "smart-buffer";
      packageName = "smart-buffer";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/smart-buffer/-/smart-buffer-4.2.0.tgz";
        sha512 = "94hK0Hh8rPqQl2xXc3HsaBoOXKV20MToPkcXvwbISWLEs+64sBq5kFgn2kJDHb1Pry9yrP0dxrCI9RRci7RXKg==";
      };
    };
    "socks-2.6.2" = {
      name = "socks";
      packageName = "socks";
      version = "2.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/socks/-/socks-2.6.2.tgz";
        sha512 = "zDZhHhZRY9PxRruRMR7kMhnf3I8hDs4S3f9RecfnGxvcBHQcKcIH/oUcEWffsfl1XxdYlA7nnlGbbTvPz9D8gA==";
      };
    };
    "socks-proxy-agent-6.2.0" = {
      name = "socks-proxy-agent";
      packageName = "socks-proxy-agent";
      version = "6.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/socks-proxy-agent/-/socks-proxy-agent-6.2.0.tgz";
        sha512 = "wWqJhjb32Q6GsrUqzuFkukxb/zzide5quXYcMVpIjxalDBBYy2nqKCFQ/9+Ie4dvOYSQdOk3hUlZSdzZOd3zMQ==";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "sprintf-js-1.1.2" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.1.2.tgz";
        sha512 = "VE0SOVEHCk7Qc8ulkWw3ntAzXuqf7S2lvwQaDLRnUeIEaKNQJzV6BwmLKhOqT61aGhfUMrXeaBk+oDGCzvhcug==";
      };
    };
    "ssri-9.0.1" = {
      name = "ssri";
      packageName = "ssri";
      version = "9.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ssri/-/ssri-9.0.1.tgz";
        sha512 = "o57Wcn66jMQvfHG1FlYbWeZWW/dHZhJXjpIcTfXldXEk5nz5lStPo3mK0OJQfGR3RbZUlbISexbljkJzuEj/8Q==";
      };
    };
    "string-width-4.2.3" = {
      name = "string-width";
      packageName = "string-width";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz";
        sha512 = "wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g==";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "strip-ansi-6.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
        sha512 = "Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==";
      };
    };
    "supports-color-7.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz";
        sha512 = "qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
      };
    };
    "supports-preserve-symlinks-flag-1.0.0" = {
      name = "supports-preserve-symlinks-flag";
      packageName = "supports-preserve-symlinks-flag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-preserve-symlinks-flag/-/supports-preserve-symlinks-flag-1.0.0.tgz";
        sha512 = "ot0WnXS9fgdkgIcePe6RHNk1WA8+muPa6cSjeR3V8K27q9BB1rTE3R1p7Hv0z1ZyAc8s6Vvv8DIyWf681MAt0w==";
      };
    };
    "svg-pathdata-6.0.3" = {
      name = "svg-pathdata";
      packageName = "svg-pathdata";
      version = "6.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/svg-pathdata/-/svg-pathdata-6.0.3.tgz";
        sha512 = "qsjeeq5YjBZ5eMdFuUa4ZosMLxgr5RZ+F+Y1OrDhuOCEInRMA3x74XdBtggJcj9kOeInz0WE+LgCPDkZFlBYJw==";
      };
    };
    "svg2ttf-6.0.3" = {
      name = "svg2ttf";
      packageName = "svg2ttf";
      version = "6.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/svg2ttf/-/svg2ttf-6.0.3.tgz";
        sha512 = "CgqMyZrbOPpc+WqH7aga4JWkDPso23EgypLsbQ6gN3uoPWwwiLjXvzgrwGADBExvCRJrWFzAeK1bSoSpE7ixSQ==";
      };
    };
    "svgicons2svgfont-10.0.6" = {
      name = "svgicons2svgfont";
      packageName = "svgicons2svgfont";
      version = "10.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/svgicons2svgfont/-/svgicons2svgfont-10.0.6.tgz";
        sha512 = "fUgQEVg3XwTbOHvlXahHGqCet5Wvfo1bV4DCvbSRvjsOCPCRunYbG4dUJCPegps37BMph3eOrfoobhH5AWuC6A==";
      };
    };
    "svgpath-2.5.0" = {
      name = "svgpath";
      packageName = "svgpath";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/svgpath/-/svgpath-2.5.0.tgz";
        sha512 = "o/vohwqjUO9nDAh4rcjE3KaW/v//At8UJu2LJMybXidf5QLQLVA4bxH0//4YCsr+1H4Gw1Wi/Jc62ynzSBYidw==";
      };
    };
    "tar-6.1.11" = {
      name = "tar";
      packageName = "tar";
      version = "6.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/tar/-/tar-6.1.11.tgz";
        sha512 = "an/KZQzQUkZCkuoAA64hM92X0Urb6VpRhAFllDzz44U2mcD5scmT3zBc4VgVpkugF580+DQn8eAFSyoQt0tznA==";
      };
    };
    "temp-0.9.4" = {
      name = "temp";
      packageName = "temp";
      version = "0.9.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/temp/-/temp-0.9.4.tgz";
        sha512 = "yYrrsWnrXMcdsnu/7YMYAofM1ktpL5By7vZhf15CrXijWWrEYZks5AXBudalfSWJLlnen/QUJUB5aoB0kqZUGA==";
      };
    };
    "to-regex-range-5.0.1" = {
      name = "to-regex-range";
      packageName = "to-regex-range";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-5.0.1.tgz";
        sha512 = "65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==";
      };
    };
    "ttf2eot-3.1.0" = {
      name = "ttf2eot";
      packageName = "ttf2eot";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ttf2eot/-/ttf2eot-3.1.0.tgz";
        sha512 = "aHTbcYosNHVqb2Qtt9Xfta77ae/5y0VfdwNLUS6sGBeGr22cX2JDMo/i5h3uuOf+FAD3akYOr17+fYd5NK8aXw==";
      };
    };
    "ttf2woff-3.0.0" = {
      name = "ttf2woff";
      packageName = "ttf2woff";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ttf2woff/-/ttf2woff-3.0.0.tgz";
        sha512 = "OvmFcj70PhmAsVQKfC15XoKH55cRWuaRzvr2fpTNhTNer6JBpG8n6vOhRrIgxMjcikyYt88xqYXMMVapJ4Rjvg==";
      };
    };
    "ttf2woff2-4.0.5" = {
      name = "ttf2woff2";
      packageName = "ttf2woff2";
      version = "4.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ttf2woff2/-/ttf2woff2-4.0.5.tgz";
        sha512 = "zpoU0NopfjoyVqkFeQ722SyKk/n607mm5OHxuDS/wCCSy82B8H3hHXrezftA2KMbKqfJIjie2lsJHdvPnBGbsw==";
      };
    };
    "unc-path-regex-0.1.2" = {
      name = "unc-path-regex";
      packageName = "unc-path-regex";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/unc-path-regex/-/unc-path-regex-0.1.2.tgz";
        sha1 = "e73dd3d7b0d7c5ed86fbac6b0ae7d8c6a69d50fa";
      };
    };
    "underscore.string-3.3.6" = {
      name = "underscore.string";
      packageName = "underscore.string";
      version = "3.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore.string/-/underscore.string-3.3.6.tgz";
        sha512 = "VoC83HWXmCrF6rgkyxS9GHv8W9Q5nhMKho+OadDJGzL2oDYbYEppBaCMH6pFlwLeqj2QS+hhkw2kpXkSdD1JxQ==";
      };
    };
    "unique-filename-1.1.1" = {
      name = "unique-filename";
      packageName = "unique-filename";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/unique-filename/-/unique-filename-1.1.1.tgz";
        sha512 = "Vmp0jIp2ln35UTXuryvjzkjGdRyf9b2lTXuSYUiPmzRcl3FDtYqAwOnTJkAngD9SWhnoJzDbTKwaOrZ+STtxNQ==";
      };
    };
    "unique-slug-2.0.2" = {
      name = "unique-slug";
      packageName = "unique-slug";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/unique-slug/-/unique-slug-2.0.2.tgz";
        sha512 = "zoWr9ObaxALD3DOPfjPSqxt4fnZiWblxHIgeWqW8x7UqDzEtHEQLzji2cuJYQFCU6KmoJikOYAZlrTHHebjx2w==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "v8flags-3.2.0" = {
      name = "v8flags";
      packageName = "v8flags";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/v8flags/-/v8flags-3.2.0.tgz";
        sha512 = "mH8etigqMfiGWdeXpaaqGfs6BndypxusHHcv2qSHyZkGEznCd/qAXCWWRzeowtL54147cktFOC4P5y+kl8d8Jg==";
      };
    };
    "varstream-0.3.2" = {
      name = "varstream";
      packageName = "varstream";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/varstream/-/varstream-0.3.2.tgz";
        sha1 = "18ac6494765f3ff1a35ad9a4be053bec188a5de1";
      };
    };
    "which-1.3.1" = {
      name = "which";
      packageName = "which";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.3.1.tgz";
        sha512 = "HxJdYWq1MTIQbJ3nw0cqssHoTNU267KlrDuGZ1WYlxDStUtKUhOaJmh112/TZmHxxUfuJqPXSOm7tDyas0OSIQ==";
      };
    };
    "which-2.0.2" = {
      name = "which";
      packageName = "which";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
        sha512 = "BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
      };
    };
    "wide-align-1.1.5" = {
      name = "wide-align";
      packageName = "wide-align";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/wide-align/-/wide-align-1.1.5.tgz";
        sha512 = "eDMORYaPNZ4sQIuuYPDHdQvf4gyCF9rEEV/yPxGfwPkRodwEgiMUUXTx/dex+Me0wxx53S+NgUHaP7y3MGlDmg==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
  };
  args = {
    name = "sandstorm-fonts";
    packageName = "sandstorm-fonts";
    version = "0.1.0";
    src = ./.;
    dependencies = [
      sources."@gar/promisify-1.1.3"
      sources."@npmcli/fs-2.1.0"
      sources."@npmcli/move-file-2.0.0"
      sources."@tootallnate/once-2.0.0"
      sources."@xmldom/xmldom-0.7.5"
      sources."abbrev-1.1.1"
      sources."agent-base-6.0.2"
      sources."agentkeepalive-4.2.1"
      sources."aggregate-error-3.1.0"
      sources."ansi-regex-5.0.1"
      sources."ansi-styles-4.3.0"
      sources."aproba-2.0.0"
      sources."are-we-there-yet-3.0.0"
      (sources."argparse-1.0.10" // {
        dependencies = [
          sources."sprintf-js-1.0.3"
        ];
      })
      sources."array-each-1.0.1"
      sources."array-slice-1.1.0"
      sources."async-3.2.3"
      sources."balanced-match-1.0.2"
      sources."bindings-1.5.0"
      sources."brace-expansion-1.1.11"
      sources."braces-3.0.2"
      sources."bufferstreams-3.0.0"
      (sources."cacache-16.1.0" // {
        dependencies = [
          sources."brace-expansion-2.0.1"
          sources."glob-8.0.3"
          sources."minimatch-5.1.0"
        ];
      })
      sources."chalk-4.1.2"
      sources."chownr-2.0.0"
      sources."clean-stack-2.2.0"
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."color-support-1.1.3"
      sources."colors-1.1.2"
      sources."commander-7.2.0"
      sources."concat-map-0.0.1"
      sources."console-control-strings-1.1.0"
      sources."core-util-is-1.0.3"
      sources."cubic2quad-1.2.1"
      sources."dateformat-3.0.3"
      sources."debug-4.3.4"
      sources."delegates-1.0.0"
      sources."depd-1.1.2"
      sources."detect-file-1.0.0"
      sources."emoji-regex-8.0.0"
      (sources."encoding-0.1.13" // {
        dependencies = [
          sources."iconv-lite-0.6.3"
        ];
      })
      sources."env-paths-2.2.1"
      sources."err-code-2.0.3"
      sources."esprima-4.0.1"
      sources."eventemitter2-0.4.14"
      sources."exit-0.1.2"
      sources."expand-tilde-2.0.2"
      sources."extend-3.0.2"
      sources."file-uri-to-path-1.0.0"
      sources."fill-range-7.0.1"
      (sources."findup-sync-0.3.0" // {
        dependencies = [
          sources."glob-5.0.15"
        ];
      })
      sources."fined-1.2.0"
      sources."flagged-respawn-1.0.1"
      sources."for-in-1.0.2"
      sources."for-own-1.0.0"
      sources."fs-minipass-2.1.0"
      sources."fs.realpath-1.0.0"
      sources."function-bind-1.1.1"
      sources."gauge-4.0.4"
      sources."geometry-interfaces-1.1.4"
      sources."getobject-1.0.2"
      sources."glob-7.1.7"
      sources."global-modules-1.0.0"
      sources."global-prefix-1.0.2"
      sources."graceful-fs-4.2.10"
      sources."grunt-1.5.3"
      (sources."grunt-cli-1.4.3" // {
        dependencies = [
          sources."nopt-4.0.3"
        ];
      })
      sources."grunt-known-options-2.0.0"
      sources."grunt-legacy-log-3.0.0"
      sources."grunt-legacy-log-utils-2.1.0"
      (sources."grunt-legacy-util-2.0.1" // {
        dependencies = [
          sources."which-2.0.2"
        ];
      })
      sources."grunt-webfonts-4.0.1"
      sources."has-1.0.3"
      sources."has-flag-4.0.0"
      sources."has-unicode-2.0.1"
      sources."homedir-polyfill-1.0.3"
      sources."hooker-0.2.3"
      sources."http-cache-semantics-4.1.0"
      sources."http-proxy-agent-5.0.0"
      sources."https-proxy-agent-5.0.1"
      sources."humanize-ms-1.2.1"
      sources."iconv-lite-0.4.24"
      sources."imurmurhash-0.1.4"
      sources."indent-string-4.0.0"
      sources."infer-owner-1.0.4"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."ini-1.3.8"
      sources."interpret-1.1.0"
      sources."ip-1.1.8"
      sources."is-absolute-1.0.0"
      sources."is-core-module-2.9.0"
      sources."is-extglob-2.1.1"
      sources."is-fullwidth-code-point-3.0.0"
      sources."is-glob-4.0.3"
      sources."is-lambda-1.0.1"
      sources."is-number-7.0.0"
      sources."is-plain-object-2.0.4"
      sources."is-relative-1.0.0"
      sources."is-unc-path-1.0.0"
      sources."is-windows-1.0.2"
      sources."isarray-0.0.1"
      sources."isexe-2.0.0"
      sources."isobject-3.0.1"
      sources."js-yaml-3.14.1"
      sources."kind-of-6.0.3"
      (sources."liftup-3.0.1" // {
        dependencies = [
          sources."findup-sync-4.0.0"
        ];
      })
      sources."lodash-4.17.21"
      sources."lru-cache-7.10.1"
      sources."make-fetch-happen-10.1.5"
      sources."make-iterator-1.0.1"
      sources."map-cache-0.2.2"
      sources."memorystream-0.3.1"
      sources."microbuffer-1.0.0"
      sources."micromatch-4.0.5"
      sources."minimatch-3.0.8"
      sources."minimist-1.2.6"
      sources."minipass-3.1.6"
      sources."minipass-collect-1.0.2"
      sources."minipass-fetch-2.1.0"
      sources."minipass-flush-1.0.5"
      sources."minipass-pipeline-1.2.4"
      sources."minipass-sized-1.0.3"
      sources."minizlib-2.1.2"
      sources."mkdirp-1.0.4"
      sources."ms-2.1.2"
      sources."nan-2.16.0"
      sources."neatequal-1.0.0"
      sources."negotiator-0.6.3"
      (sources."node-gyp-9.0.0" // {
        dependencies = [
          sources."nopt-5.0.0"
          sources."which-2.0.2"
        ];
      })
      sources."nopt-3.0.6"
      sources."npmlog-6.0.2"
      sources."object.defaults-1.1.0"
      sources."object.map-1.0.1"
      sources."object.pick-1.3.0"
      sources."once-1.4.0"
      sources."os-homedir-1.0.2"
      sources."os-tmpdir-1.0.2"
      sources."osenv-0.1.5"
      sources."p-map-4.0.0"
      sources."pako-1.0.11"
      sources."parse-filepath-1.0.2"
      sources."parse-passwd-1.0.0"
      sources."path-is-absolute-1.0.1"
      sources."path-parse-1.0.7"
      sources."path-root-0.1.1"
      sources."path-root-regex-0.1.2"
      sources."picomatch-2.3.1"
      sources."promise-inflight-1.0.1"
      sources."promise-retry-2.0.1"
      (sources."readable-stream-3.6.0" // {
        dependencies = [
          sources."string_decoder-1.3.0"
        ];
      })
      sources."rechoir-0.7.1"
      sources."resolve-1.22.0"
      sources."resolve-dir-1.0.1"
      sources."retry-0.12.0"
      sources."rimraf-3.0.2"
      sources."safe-buffer-5.2.1"
      sources."safer-buffer-2.1.2"
      sources."sax-1.2.4"
      (sources."semver-7.3.7" // {
        dependencies = [
          sources."lru-cache-6.0.0"
        ];
      })
      sources."set-blocking-2.0.0"
      sources."signal-exit-3.0.7"
      sources."smart-buffer-4.2.0"
      sources."socks-2.6.2"
      sources."socks-proxy-agent-6.2.0"
      sources."sprintf-js-1.1.2"
      sources."ssri-9.0.1"
      sources."string-width-4.2.3"
      sources."string_decoder-0.10.31"
      sources."strip-ansi-6.0.1"
      sources."supports-color-7.2.0"
      sources."supports-preserve-symlinks-flag-1.0.0"
      sources."svg-pathdata-6.0.3"
      (sources."svg2ttf-6.0.3" // {
        dependencies = [
          sources."argparse-2.0.1"
        ];
      })
      sources."svgicons2svgfont-10.0.6"
      sources."svgpath-2.5.0"
      sources."tar-6.1.11"
      (sources."temp-0.9.4" // {
        dependencies = [
          sources."mkdirp-0.5.6"
          sources."rimraf-2.6.3"
        ];
      })
      sources."to-regex-range-5.0.1"
      (sources."ttf2eot-3.1.0" // {
        dependencies = [
          sources."argparse-2.0.1"
        ];
      })
      (sources."ttf2woff-3.0.0" // {
        dependencies = [
          sources."argparse-2.0.1"
        ];
      })
      sources."ttf2woff2-4.0.5"
      sources."unc-path-regex-0.1.2"
      sources."underscore.string-3.3.6"
      sources."unique-filename-1.1.1"
      sources."unique-slug-2.0.2"
      sources."util-deprecate-1.0.2"
      sources."v8flags-3.2.0"
      (sources."varstream-0.3.2" // {
        dependencies = [
          sources."readable-stream-1.1.14"
        ];
      })
      sources."which-1.3.1"
      sources."wide-align-1.1.5"
      sources."wrappy-1.0.2"
      sources."yallist-4.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Fonts for sandstorm.";
    };
    production = false;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
